# Spectral Mesh Flattening

by Ana + Gabrielle

In [58]:
import trimesh
import numpy as np

In [59]:
face = trimesh.load("Face.obj")
print(face.faces)
print(face.vertex_faces)

[[   0    1    2]
 [   3    4    5]
 [   6    7    8]
 ...
 [1363 1365 1366]
 [1367 1368 1369]
 [1367 1369 1370]]
[[ 977  976  975 ...   -1   -1   -1]
 [ 975  974  787 ...   -1   -1   -1]
 [ 977  785  782 ...   -1   -1   -1]
 ...
 [2516   -1   -1 ...   -1   -1   -1]
 [2517 2516   -1 ...   -1   -1   -1]
 [2517   -1   -1 ...   -1   -1   -1]]


In [60]:
def boundary(mesh):
    """ A function to find the boundary edges and vertices of a mesh. """

    boundary_edges = []
    boundary_vertices = []

    edges = mesh.edges
    faces = mesh.faces
    vertex_faces = mesh.vertex_faces

    for i in range(len(edges)):

        edge = edges[i]
        v1, v2 = edge
        v1_faces = [j for j in vertex_faces[v1] if j != -1]
        v1v2_faces = [j for j in v1_faces if j in vertex_faces[v2]]
        
        if len(v1v2_faces) == 1:
            boundary_edges  = boundary_edges + [edge]
            boundary_vertices = boundary_vertices + [v1, v2]
        
    boundary_vertices = np.unique(np.array(boundary_vertices))
    
    return boundary_edges, boundary_vertices